### ISSUE TITLE
Windows build broken in CI

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-link-cpp#12]
The windows build seems to be broken in CI, it complains about compiler version. See https://github.com/bitcraze/crazyflie-link-cpp/runs/2564641059 for example.

This needs to be investigated. It is an odd problem since I just tried to build in a newly installed VisualStudio on Windows 10 and it does work out of the box.

**Comment by whoenig** [comment]
Is the a way to see which Visual Studio version the github action is using? We need VS2019 (or older), or we would need to change the CI to build libusb itself, rather than relying on the prebuilt libs.

**Comment by ataffanel** [comment]
Building libusb would help for #13, but I am not so good with cmake so I do not know where to get started ...

The gihub hosted Windows runner seems to come with [VS2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019). But if windows lib build is so brittle and since we only have one dependency, maybe compiling libusb from source is the safest to keep the CI running.

**Comment by whoenig** [comment]
One problem is that libusb simply comes with VS project files, no cmake support. So we would need to maintain the cmake part, if libusb gets updated. In general, this is only an issue when big refactorings happen (e.g., renaming of source files).

I think it would be pretty easy to compile it using CMake, all we need is to mimic https://github.com/libusb/libusb/blob/master/msvc/libusb_static_2019.vcxproj (i.e., there are about 20 c source files to list, a few pre-processor defines and nothing else). One challenge might be to get to the source code: traditionally, I would use a git submodule, but this seems strange if we then only use it one a single platform? Another option might be to download the source archive (similar to how we currently download the binary distribution), but I do have less experience with that and I am not sure how bullet-proof that is.
