### ISSUE TITLE
Crash when accessing Crazyradio with libusb-win32 driver

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-link-cpp#13]
On Windows, the documented driver to use with the Crazyflie is "libusb-win32". This is a libusb0 driver and, as far as I understand, libusb1 is not compatible with it.

Libusb1, which is used by this lib, is compatible with the WinUSB driver.

The problem is that, when a radio is installed with a libusb-win32 driver, it is detected by libusb1 but as soon as it is accessed it crashes the program (be it one of the example or the full python). When running the scan example I get this exception:
```
Exception thrown at 0x00007FF8EED53416 (ntdll.dll) in example_scan.exe: 0xC0000005: Access violation writing location 0x000000FDFDFDFD30.
```

On the same machine the example works when the Crazyradio has the WinUSB driver installed.

This behavior can be observed using pyusb on python will libusb1 backend as well so it seems to be a problem in libusb1. Oddly enough, visualstudio does not give me a backtrace that touches our code or libusb:
![image](https://user-images.githubusercontent.com/6381499/117981453-52e04480-b335-11eb-8064-1180784e8017.png)

In order to use this link implementation from the Crazyflie python lib on Windows we need to get the users to transition from libusb-win32 to WinUSB, for example by displaying an error message if a Crazyradio with libusb-win32 driver is detected. To do so we need to solve this bug.

**Comment by whoenig** [comment]
Most likely related to https://github.com/libusb/libusb/issues/844. This has been fixed, but there is no libusb release that includes the fix, yet. One way to debug those sorts of crashes is to set the `LIBUSB_DEBUG=4` environment variable.

**Comment by mcuee** [comment]
libusb is kind of compatible with libusb0.sys driver as well but there are many issues, so it is not recommended to use libusb0.sys for libusb Windows.

https://github.com/libusb/libusb/issues/844 is actually talking about libusbk.sys.

**Comment by mcuee** [comment]
libusb-win32 (which contains libusb0.sys and libusb0.dll) is in a bug fixed mode and it does not work well under libusb-1.0 Windows. 
https://github.com/mcuee/libusb-win32

libusbk project is now considered as not maintained so we will recommend people to move to WinUSB. It works better with libusb-1.0 Windows than libusb0.sys driver but there are still a few issues.
https://github.com/mcuee/libusbk

**Comment by mcuee** [comment]
libusbk is again in active development. 

For libusb Windows project, we recommend to use WinUSB as the USB driver of choice. If you hit into the limitation of WinUSB, then you can try libusbk.sys. libusb0.sys is the last choice (not recommended as of now).

**Comment by ataffanel** [comment]
Thanks for the information, good to know! I plan to transition to WinUSB and to add the MS OS Descriptor to the Crazyradio firmware in the next batch to allow for driver-less experience on Windows (finally ....).

However we already have quite a lot of people with libusb0 or libusbk driver setup. This is why, both for the CPP link in this repos and our Python lib using pyusb, we need a solution that either work for both driver or at least detect that libusb0 is being used and instruct the user to install WinUSB instead using Zadig (so the crash was a problem).

I have not had time to work on that lately but last time I checked, using master of libusb1 did work. I saw your call for contribution for release on the libusb repos, maybe I can start having a look at that and help out a bit. It does seem that a release of libusb will allow us to close this issue and move forward with the transition to WinUSB.

**Comment by whoenig** [comment]
@ataffanel For windows we simply use libusb as a submodule, so we are actually not bound to using a released version. Just testing is always annoying, of course.

**Comment by mcuee** [comment]
FYI, libusb0.sys support under libusb Windows is pretty broken now, unfortunately the only active Windows developer Chris is probably busy so he has not been able to look at the issues yet.
Ref: 
https://github.com/libusb/libusb/issues/94
https://github.com/libusb/libusb/issues/761

**Comment by knmcguire** [comment]
Just a update , it seems that there is quite some activity now in the above issues and we should keep an eye on this pull request being merged: https://github.com/libusb/libusb/pull/1016

**Comment by knmcguire** [comment]
Hi! 

If I update the libusb submodule to the latest master, the windows crash is resolved. When I try example_scan, the LED on the crazyradio turns red and all and the program completes without an error.

The only weird thing is, is that it is not able to detect my crazyflie on channel 80 with E7E7E7E702 address.... so not exactly sure what is going on there.

**Comment by knmcguire** [comment]
wait, if I put it on the standard channel it says:

radio://*/0/2M/E7E7E7E7E7

Seems to be working fine ! I'll make a pull request to update the submodule

**Comment by whoenig** [comment]
Can we close this issue then?

**Comment by knmcguire** [comment]
Yeah let's do it! We can always reopen if the new problem comes along
