### ISSUE TITLE
Client uses old param API error

### ISSUE THREAD

**Issue by Steven-Sorokin** [bitcraze/crazyflie-link-cpp#7]
Hello bitcraze,
I'm have a crazyflie 2.0 and used [this](https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/functional-areas/crtp/crtp_parameters/#toc-access) documentation for the basis of the program bellow.

`Client uses old param API error`
 
I recieved the message displayed above from the console after trying to get the next toc element using the following code:
``` c
Connection con("usb://0");

// empty receiver queue
while (true)
{
    Packet p = con.recv(100);
    if (!p)
    {
        break;
    }
}
Packet p;
p.setPort(2);   
p.setChannel(0); 
int getNextTocElementCode = 1;
p.setPayloadSize(sizeof(uint32_t));
std::memcpy(p.payload(), &getNextTocElementCode, sizeof(getNextTocElementCode));

con.send(p);
Packet p_recv;
do
{
    p_recv = con.recv(0);
    if(p_recv.port()==0)
        std::cout << p_recv.payload() << std::endl;

} while (p_recv.port() != 2);
std::cout << p_recv << std::endl;
```
The code above is trying to receive an element from the TOC but instead it receives an error which is directed to the console, followed by a packet that doesn't correspond to the protocol stated in the Bitcraze documentation:

`Packet(channel=0,port=2,safelinkUp=0,safelinkDown=0,data=1 214 70 138 110 185 ,seq=4)`

**Comment by Steven-Sorokin** [comment]
![image](https://user-images.githubusercontent.com/67019760/115994803-30ce8e80-a5e1-11eb-8cb3-2b745ecfe593.png)

**Comment by whoenig** [comment]
I think you correctly answered this question - new code should use V2 of the API, since current firmware versions actually have more than 255 parameters. You can find the code in the firmware at https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/param.c#L68-L71.

**Comment by trakevital** [comment]
![image](https://user-images.githubusercontent.com/32649570/116003523-fa0b6f00-a606-11eb-8ecb-44e6c1842256.png)

How could it be that `CMD_RESET` and `CMD_GET_ITEM` are the same value?

**Comment by whoenig** [comment]
`CMD_RESET` doesn't seem to be used in the current code.

**Comment by knmcguire** [comment]
It seems that this issue has been resolved, so I'll close it.
